natsuk4ze/gal

- CHANGELOG.md
- README.md
- android/src/main/java/studio/midoridesign/gal/GalPlugin.java
- example/pubspec.lock
- ios/Classes/GalPlugin.swift
- lib/gal.dart
- lib/gal_exception.dart
- pubspec.yaml
> Add exceptions

- README.md
- android/src/main/java/studio/midoridesign/gal/GalPlugin.java
- example/android/app/src/main/AndroidManifest.xml
- example/ios/Podfile.lock
- example/lib/main.dart
- ios/Classes/GalPlugin.swift
- lib/gal.dart
- lib/gal_method_channel.dart
- lib/gal_platform_interface.dart
> Handle permission

- .github/workflows/ci.yml
- example/integration_test/integration_test.dart
> Fix workflow

- android/src/main/java/studio/midoridesign/gal/GalPlugin.java
> Return false when request code invalid

- android/src/main/java/studio/midoridesign/gal/GalPlugin.java
'Google photos' in Android 23 is ok.
> Fix open() in 'gallery' app with android 23 shows gallery/pictures

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/workflows/ci.yml
- .gitignore
- android/src/main/java/studio/midoridesign/gal/GalPlugin.java
- example/android/app/src/main/AndroidManifest.xml
- example/integration_test/integration_test.dart
- example/integration_test/test_app.dart
- example/ios/Runner/Info.plist
- example/lib/main.dart
- ios/Classes/GalPlugin.swift
- lib/src/gal.dart
- lib/src/gal_method_channel.dart
- lib/src/gal_platform_interface.dart
> Saving to album

- lib/src/gal_platform.dart
- Close #96 
- Close #95 
- Close #98
> Fix gal platform

- android/build.gradle
- android/src/main/java/studio/midoridesign/gal/GalPlugin.java
- ios/Classes/GalPlugin.swift
> Fix auto file conversion

- ios/Classes/GalPlugin.swift
> Update `putImageBytes` in swift

- .github/workflows/ci.yml
> Update java for ci

- lib/src/gal_exception.dart
⚠️ This PR contains breaking change
> Remove `GalExceptionType.notHandle`

- .github/workflows/ci.yml
Fix `Package install error: Failure [INSTALL_FAILED_INSUFFICIENT_STORAGE]` in [low android version](https://github.com/natsuk4ze/gal/actions/runs/6516829553/job/17700741967)
> Increase android storage in test

- README.md
Fix typos in `README.md`
Fix typos in `README.md` and update the status of the projects that using `gal` plugin
None
> Update README.md to fix typos

- .github/workflows/ci.yml
For details: [log](https://arc.net/l/quote/kqvcuqep)
> Fix INSTALL_FAILED_INSUFFICIENT_STORAGE in CI with Android

- .github/workflows/cancel.yml
- .github/workflows/ci.yml
A special token is required to trigger on a forked PR. Therefore, isolate the workflow.
- https://github.com/styfle/cancel-workflow-action/tree/0.12.1/?tab=readme-ov-file#advanced-pull-requests-from-forks
> Add cancel workflow

- CHANGELOG.md
- README.md
- example/pubspec.yaml
- pubspec.yaml
> Update to 2.3.1

- .github/workflows/ci_android.yml
- .github/workflows/ci_ios.yml
- .github/workflows/ci_macos.yml
- .github/workflows/ci_windows.yml
_Please change this text to a brief statement of purpose or overview._
-
> Optimize CI

- .github/workflows/ci.yml
_Please change this text to a brief statement of purpose or overview._
-
> feat: add-manual-trigger-to-ci

- .github/dependabot.yml
_Please change this text to a brief statement of purpose or overview._
-
> dependabotの設定に各プラットフォーム向けエコシステムを追加

- android/build.gradle
- example/android/app/build.gradle
- example/android/gradle.properties
- example/android/gradle/wrapper/gradle-wrapper.properties
- example/android/settings.gradle
> Revert "chore(android): update Java compileOptions to VERSION_11 to suppress obsolete warnings"

- .github/workflows/ci_android.yml
- android/build.gradle
- example/android/app/build.gradle
- example/android/gradle.properties
- example/android/gradle/wrapper/gradle-wrapper.properties
- example/android/settings.gradle
> "chore(android): update Java compileOptions to VERSION_11 to suppress obsolete warnings""

- .github/workflows/claude.yml
_Please change this text to a brief statement of purpose or overview._
-
> Add actions write permission
